### ISSUE TITLE
Provide swagger documentation

### ISSUE THREAD

**Issue by bametz** [rocketbeans/rbtv-apidoc#1]
As a developer I would like to try out the API without writing code in order to quickly get a feel of the API, the data and if it suffices to my needs.

**Proposed Solution:** OpenAPI (swagger) documentation endpoint that allows for a live try out of the API. 
Authentication and authorization could be covered via the swagger endpoint as well (OAuth).

**Comment by r0oto0r** [comment]
Hey there, we don't have that on our roadmap right now and probably not gonna happen anytime soon. As it is also a quite old request I'm going to close it for now. Sorry for the inconvenience!
