### ISSUE TITLE
Type definition for scheduleItem needs an update

### ISSUE THREAD

**Issue by TechInterMezzo** [rocketbeans/rbtv-apidoc#2]
episodeImage is now episodeImages and an array of objects instead of a string.

https://github.com/rocketbeans/rbtv-apidoc/blob/4ca8a413c064840730b58bb2b46dc108bf566dd0/response/schedule/SchedulePublic.ts#L11

Furthermore a property named links got added.

**Comment by wilkemeyer** [comment]
Thanks for reporting! 

episodeImage should still be present and behave as before episodeImages got added

I'll schedule an apidoc update for the next days :)

**Comment by TechInterMezzo** [comment]
Any updates?

**Comment by r0oto0r** [comment]
Fixed in current release!
