### ISSUE TITLE
`IRaffleTeaser` and `authProvider` are not defined anywhere

### ISSUE THREAD

**Issue by Dobatymo** [rocketbeans/rbtv-apidoc#4]
`IRaffleTeaser` used here https://github.com/rocketbeans/rbtv-apidoc/blob/91e85c2b60c25a4dac50a2f1f6089b7daaa397af/response/blog/BlogPublic.ts#L3 but never defined.

`authProvider` used here https://github.com/rocketbeans/rbtv-apidoc/blob/91e85c2b60c25a4dac50a2f1f6089b7daaa397af/response/frontend/FrontendPublic.ts#L10 but never defined.

**Comment by r0oto0r** [comment]
I'm revising the entire API documentation at the moment and will update it in the coming days. Will take a look at this issue as well. Thanks for reporting!

**Comment by r0oto0r** [comment]
Fixed in current release!
